# yaml es como JSON pero "sin tanto ruido"
news_sites:                                                                   # Esto luego se volvera un diccionario
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:                                                                  # Agregamos la secci칩n de 'queries' que ser치n los links dentro de las paginas web a lo que le haremos el "web scrapping"
      homepage_article_links: '.regionals__title a'                           # Usando selectores de CSS indicamos que elemento le haremos el 'web scrappin', pueden ser unos cuantos y cientos de links (chequear la p치gina para ver los selectores a utilizar)
      article_body: '.columm2'                                                # A침ado los selectores para el cuerpo de la noticia
      article_title: '.sc__header h1'                                         # Selector para el titulo de la noticia
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.c_h a'
      article_body: '.a_c'
      article_title: '.a_e_txt h1' 
